# Generated by Django 3.1.4 on 2021-09-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPage',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_question_page', to='core.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('placeholder', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('SUB', 'SUBJECTIVE')], default=None, max_length=50, null=True)),
                ('variant', models.CharField(blank=True, choices=[('RADIO', 'RADIO'), ('CHECKBOX', 'CHECKBOX')], default=None, max_length=50, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('options', models.ManyToManyField(blank=True, to='core.MCQQuestionOption')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_question', to='core.survey')),
            ],
        ),
    ]
