# Generated by Django 3.1.4 on 2021-09-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210926_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questionpage', to='core.questionpage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_question', to='core.survey'),
        ),
    ]
