# Generated by Django 3.1.4 on 2021-09-27 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210926_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionpage', to='core.questionpage'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question', to='core.survey'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question_page', to='core.survey'),
        ),
    ]
